# Generated by Django 5.2.3 on 2026-09-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(blank=True, max_length=500)),
                ('task_assignee', models.CharField(max_length=50)),
                ('task_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('task_status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TO_DO', max_length=15)),
                ('task_due_date', models.DateField()),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
