# Generated by Django 5.2.2 on 2026-09-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_task_tracker_dashboard_task_database_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_database',
            name='user',
        ),
    ]
