# Generated by Django 5.2.2 on 2026-09-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_database_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_database',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
